;
; File generated by cc65 v 2.18 - Ubuntu 2.18-1
;
	.fopt		compiler,"cc65 v 2.18 - Ubuntu 2.18-1"
	.setcpu		"65C02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_cgetc
	.import		_cputc
	.import		_cputs
	.export		_c
	.export		_main

.segment	"RODATA"

L0003:
	.byte	$48,$65,$6C,$6C,$6F,$2C,$20,$63,$6F,$6E,$69,$6F,$20,$66,$72,$6F
	.byte	$6D,$20,$43,$0A,$0A,$00

.segment	"BSS"

_c:
	.res	1,$00

; ---------------------------------------------------------------
; unsigned char __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	lda     #<(L0003)
	ldx     #>(L0003)
	jsr     _cputs
	jmp     L0007
L0005:	ldy     #$00
	jsr     _cgetc
	sta     _c
	lda     _c
	jsr     _cputc
L0007:	ldx     #$00
	lda     _c
	cmp     #$1B
	jsr     boolne
	jne     L0005
	ldx     #$00
	lda     #$00
	jmp     L0001
L0001:	rts

.endproc

